### PR TITLE
Bug fixes

### LINKED ISSUE #54: [Issue] Previous Page and Next Page section
Like the title said, won't show off in the Categories section
I try so hard but it won't appear

### PR DESCRIPTION
**Pull request by fycarman**
- Moved selectors from Category constructor to Category::send(), fixes #54 
- Delete unreachable return statement from ChestShop::sendCategory()
- Fix "previous page" working as "next page"

### CODE REVIEW

File: src/muqsit/chestshop/Category.php [hunk 1]
```diff
@@ -92,6 +87,10 @@ public function send(Player $player, int $page = 1, bool $send = true) : int{
 			foreach($contents as $slot => $item){
 				$inventory->setItem($slot, $item, false);
 			}
+
+            $inventory->setItem(48, Button::get(Button::TURN_LEFT, $this->getRealName()));
```
Comment (Muqsit) [inline src/muqsit/chestshop/Category.php]: About these, I think it's far better (in terms of perf) to push these into the `$contents` array. Something like this:
```
$contents[48] = Button::get(Button::TURN_LEFT, $this->getRealName());
```
considering the frequency of this being called.

File: src/muqsit/chestshop/EventHandler.php [hunk 2]
```diff
@@ -49,9 +49,10 @@ public function handleTransaction(Player $player, Item $itemClicked, Item $itemC
 
 		if($nbt->hasTag("Button")){
 			$currentpage = $this->currentpage[$playerId = $player->getId()] ?? 1;
+			$inventoryAction->getInventory()->clearAll();//A little hack to prevent strange behaviours in mcbe 1.4+(if the second page wasn't full, items from previous page were displayed with items in the new page. Reference: https://imgur.com/a/KwOrOGi
```
Comment (Muqsit) [inline src/muqsit/chestshop/EventHandler.php]: It's more than a "little" hack, this will cause even more issues.
The correct way to fix this issue is fixing it where you fixed the buttons.
After pushing the buttons into the `$contents` array, use `Inventory::setContents($contents);`.

File: src/muqsit/chestshop/Category.php [hunk 3]
```diff
@@ -87,11 +82,14 @@ public function send(Player $player, int $page = 1, bool $send = true) : int{
...
+			$contents[48] = Button::get(Button::TURN_LEFT, $this->getRealName());
+			$contents[49] = Button::get(Button::CATEGORIES);
+			$contents[50] = Button::get(Button::TURN_RIGHT, $this->getRealName());
+
 			$inventory = $this->menu->getInventory($player);
 
-			foreach($contents as $slot => $item){
-				$inventory->setItem($slot, $item, false);
-			}
+			$inventory->setContents($contents);
```
Comment (Muqsit) [inline src/muqsit/chestshop/Category.php]: Now that that's the only method being called from `$inventory`, you might aswell directly call it as
`$this->menu->getInventory($player)->setContents($contents);`. The variable declaration becomes uneeded.
